### ISSUE TITLE
Add a TypeScript preset to turn off rules that the tsc compiler correctly transpiles

### ISSUE THREAD

**Issue by astorije** [mysticatea/eslint-plugin-es#58]
At the moment, we're using one of the `restrict-to-esNNNN` presets, which are really great. However, when using TypeScript, there are a lot of things that `tsc` transpiles correctly regardless of target, so we end up "canceling" a set of rules that are perfectly fine with TypeScript:

<details>

```yml
## ES2020

# Disallow nullish coalescing operators
# https://eslint-plugin-es.mysticatea.dev/rules/no-nullish-coalescing-operators.html
# This is correctly transpiled by TypeScript
es/no-nullish-coalescing-operators: off

# Disallow optional chaining
# https://eslint-plugin-es.mysticatea.dev/rules/no-optional-chaining.html
# This is correctly transpiled by TypeScript
es/no-optional-chaining: off

## ES2019

# Disallow optional catch binding
# https://eslint-plugin-es.mysticatea.dev/rules/no-optional-catch-binding.html
# This is correctly transpiled by TypeScript
es/no-optional-catch-binding: off

## ES2018

# Disallow async iteration
# https://eslint-plugin-es.mysticatea.dev/rules/no-async-iteration.html
# This is correctly transpiled by TypeScript
es/no-async-iteration: off

# Disallow rest/spread properties
# https://eslint-plugin-es.mysticatea.dev/rules/no-rest-spread-properties.html
# This is correctly transpiled by TypeScript
es/no-rest-spread-properties: off

## ES2017

# Disallow async function declarations
# https://eslint-plugin-es.mysticatea.dev/rules/no-async-functions.html
# This is correctly transpiled by TypeScript
es/no-async-functions: off

# Disallow trailing commas in parameter/argument lists
# https://eslint-plugin-es.mysticatea.dev/rules/no-trailing-function-commas.html
# This is correctly transpiled by TypeScript
es/no-trailing-function-commas: off
```

</details>

It would be really nice if there was an extra preset to load at the end that cancels those rule correctly, similarly to how `eslint-config-prettier` turns off all rules that are unnecessary:

```yml
extends:
  - plugin:es/restrict-to-es2015
  - plugin:es/typescript
```
